# Generated by Django 3.1.1 on 2020-12-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
