# Generated by Django 3.1.1 on 2021-07-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
