# Generated by Django 3.1.1 on 2021-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='hebrew', max_length=30, verbose_name='שפה'),
        ),
    ]
