# Generated by Django 3.2.8 on 2022-02-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210725_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'הגדרות משתמש', 'verbose_name_plural': 'הגדרות משתמשים'},
        ),
    ]
