# Generated by Django 3.1.1 on 2020-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
