# Generated by Django 3.1.1 on 2020-09-28 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_auto_20200928_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
