# Generated by Django 3.1.1 on 2020-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting', models.BooleanField(default=True, verbose_name='ניתן להגיש/לשנות הגשות')),
                ('pin_code', models.IntegerField(default=1234, verbose_name='קוד זיהוי')),
            ],
        ),
    ]
