# Generated by Django 3.1.1 on 2020-11-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_settings2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
