# Generated by Django 3.1.1 on 2020-11-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting', models.BooleanField(default=True, verbose_name='ניתן להגיש/לשנות הגשות')),
            ],
        ),
    ]
