# Generated by Django 3.1.1 on 2020-11-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
