# Generated by Django 3.1.1 on 2020-12-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_organization2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
