# Generated by Django 3.1.1 on 2020-12-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0012_shift2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
