# Generated by Django 3.1.1 on 2021-04-28 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0013_delete_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=20, verbose_name='כינוי')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('training', models.BooleanField(default=False, verbose_name='חד יומי')),
                ('night_before', models.BooleanField(default=False, verbose_name='לילה יום לפני')),
                ('morning', models.BooleanField(default=False, verbose_name='בוקר')),
                ('after_noon', models.BooleanField(default=False, verbose_name='צהריים')),
                ('night', models.BooleanField(default=False, verbose_name='לילה')),
            ],
        ),
    ]
