# Generated by Django 3.1.1 on 2021-04-28 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0015_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date2',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 11, 35, 59, 801482, tzinfo=utc), verbose_name='תאריך'),
        ),
    ]
