# Generated by Django 3.1.1 on 2021-04-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0028_auto_20210429_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings2',
        ),
    ]
