# Generated by Django 3.1.1 on 2021-07-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0030_shift1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift2',
        ),
    ]
