# Generated by Django 3.1.1 on 2021-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0031_delete_shift2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='כתובת IP')),
                ('num_tries', models.IntegerField(default=0, verbose_name='מספר ניסיונות')),
            ],
        ),
    ]
