# Generated by Django 3.1.1 on 2021-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0032_ipban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting', models.BooleanField(default=True, verbose_name='ניתן להגיש/לשנות הגשות')),
                ('pin_code', models.IntegerField(default=1234, verbose_name='קוד זיהוי')),
                ('officer', models.CharField(max_length=20, verbose_name='קצין מתקן')),
                ('city', models.CharField(max_length=100, verbose_name='עיר')),
                ('max_seq0', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי לילה לצהריים')),
                ('max_seq1', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי צהריים לבוקר')),
            ],
        ),
    ]
