# Generated by Django 3.1.1 on 2021-07-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0033_settings3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
