# Generated by Django 3.1.1 on 2021-10-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0035_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization2',
        ),
    ]
