# Generated by Django 3.1.1 on 2021-10-03 08:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0037_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 3, 8, 45, 37, 360864, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ShiftWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_week', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('M1', models.BooleanField(default=False, verbose_name='ראשון בוקר')),
                ('A1', models.BooleanField(default=False, verbose_name='ראשון צהריים')),
                ('N1', models.BooleanField(default=False, verbose_name='ראשון לילה')),
                ('P1', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R1', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes1', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M2', models.BooleanField(default=False, verbose_name='שני בוקר')),
                ('A2', models.BooleanField(default=False, verbose_name='שני צהריים')),
                ('N2', models.BooleanField(default=False, verbose_name='שני לילה')),
                ('P2', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R2', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes2', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M3', models.BooleanField(default=False, verbose_name='שלישי בוקר')),
                ('A3', models.BooleanField(default=False, verbose_name='שלישי צהריים')),
                ('N3', models.BooleanField(default=False, verbose_name='שלישי לילה')),
                ('P3', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R3', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes3', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M4', models.BooleanField(default=False, verbose_name='רביעי בוקר')),
                ('A4', models.BooleanField(default=False, verbose_name='רביעי צהריים')),
                ('N4', models.BooleanField(default=False, verbose_name='רביעי לילה')),
                ('P4', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R4', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes4', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M5', models.BooleanField(default=False, verbose_name='חמישי בוקר')),
                ('A5', models.BooleanField(default=False, verbose_name='חמישי צהריים')),
                ('N5', models.BooleanField(default=False, verbose_name='חמישי לילה')),
                ('P5', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R5', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes5', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M6', models.BooleanField(default=False, verbose_name='שישי בוקר')),
                ('A6', models.BooleanField(default=False, verbose_name='שישי צהריים')),
                ('N6', models.BooleanField(default=False, verbose_name='שישי לילה')),
                ('P6', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R6', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes6', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M7', models.BooleanField(default=False, verbose_name='שבצ בוקר')),
                ('A7', models.BooleanField(default=False, verbose_name='שבת צהריים')),
                ('N7', models.BooleanField(default=False, verbose_name='שבת לילה')),
                ('P7', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R7', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes7', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
