# Generated by Django 3.2.8 on 2022-01-20 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0038_auto_20211003_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='שם מלא')),
                ('short_name', models.CharField(max_length=20, verbose_name='שם קצר')),
            ],
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 20, 27, 52, 12920, tzinfo=utc)),
        ),
    ]
