# Generated by Django 3.2.8 on 2022-01-20 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0039_auto_20220120_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 21, 7, 27, 216437, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ArmingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='שם')),
                ('shift', models.CharField(default='', max_length=50, verbose_name='משמרת')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('time_in', models.TimeField(default=django.utils.timezone.now, verbose_name='זמן כניסה')),
                ('num_mags', models.IntegerField(default=2, verbose_name='מספר מחסניות')),
                ('hand_cuffs', models.IntegerField(default=6, verbose_name='אזיקים')),
                ('gun_case', models.IntegerField(default=6, verbose_name='פונדה')),
                ('mag_case', models.IntegerField(default=6, verbose_name='נרתיק')),
                ('keys', models.BooleanField(default=False, verbose_name='מפתחות')),
                ('radio', models.BooleanField(default=False, verbose_name='קשר')),
                ('radio_kit', models.BooleanField(default=False, verbose_name='ערכת שמע')),
                ('time_out', models.TimeField(default=django.utils.timezone.now, verbose_name='זמן יציאה')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.gun', verbose_name='מספר נשק')),
            ],
        ),
    ]
