# Generated by Django 3.2.8 on 2022-01-20 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0041_auto_20220120_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arminglog',
            name='name',
            field=models.CharField(max_length=50, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='arminglog',
            name='radio',
            field=models.BooleanField(default=False, verbose_name='קשר'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 21, 2, 43, 151142, tzinfo=utc)),
        ),
    ]
