# Generated by Django 3.2.8 on 2022-01-21 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0042_auto_20220120_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='arming_log',
            name='id_num',
            field=models.CharField(default='', max_length=50, verbose_name='תעודת זהות'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 9, 18, 12, 41175, tzinfo=utc)),
        ),
    ]
