# Generated by Django 3.2.8 on 2022-01-20 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0042_auto_20220120_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 21, 5, 6, 720351, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ArmingLog',
        ),
    ]
