# Generated by Django 3.2.8 on 2022-01-21 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0043_auto_20220121_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arming_log',
            name='shift',
        ),
        migrations.AddField(
            model_name='arming_log',
            name='shift_num',
            field=models.IntegerField(default=1, verbose_name='מספר משמרת'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 9, 36, 50, 943528, tzinfo=utc)),
        ),
    ]
