# Generated by Django 3.2.8 on 2022-01-21 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0045_auto_20220121_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 9, 52, 10, 397231, tzinfo=utc)),
        ),
    ]
