# Generated by Django 3.2.8 on 2022-01-21 15:01

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0048_auto_20220121_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='arming_log',
            name='name_checked_a',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק צהריים'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='name_checked_m',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק בוקר'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='name_checked_n',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק לילה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_safe_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת צהריים'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_safe_m',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת בוקר'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_safe_n',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת לילה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_shift_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת צהריים'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_shift_m',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת בוקר'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='num_guns_shift_n',
            field=models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת לילה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='time_checked_a',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה צהריים'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='time_checked_m',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה בוקר'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='time_checked_n',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה לילה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='valid_in',
            field=models.BooleanField(default=False, verbose_name='אישור מורשה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='valid_out',
            field=models.BooleanField(default=False, verbose_name='אישור מורשה'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 15, 1, 17, 896965, tzinfo=utc)),
        ),
    ]
