# Generated by Django 3.2.8 on 2022-01-21 16:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0049_auto_20220121_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('num_guns_safe_m', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת בוקר')),
                ('num_guns_shift_m', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת בוקר')),
                ('time_checked_m', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה בוקר')),
                ('name_checked_m', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק בוקר')),
                ('num_guns_safe_a', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת צהריים')),
                ('num_guns_shift_a', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת צהריים')),
                ('time_checked_a', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה צהריים')),
                ('name_checked_a', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק צהריים')),
                ('num_guns_safe_n', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת לילה')),
                ('num_guns_shift_n', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת לילה')),
                ('time_checked_n', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה לילה')),
                ('name_checked_n', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק לילה')),
            ],
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='name_checked_a',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='name_checked_m',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='name_checked_n',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_safe_a',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_safe_m',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_safe_n',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_shift_a',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_shift_m',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='num_guns_shift_n',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='time_checked_a',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='time_checked_m',
        ),
        migrations.RemoveField(
            model_name='arming_log',
            name='time_checked_n',
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 16, 7, 54, 302082, tzinfo=utc)),
        ),
    ]
