# Generated by Django 3.2.8 on 2022-01-23 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0051_auto_20220123_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arming_log',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='זמן יציאה'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 23, 9, 23, 13, 707379, tzinfo=utc)),
        ),
    ]
