# Generated by Django 3.2.8 on 2022-01-23 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0052_auto_20220123_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='arming_log',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 23, 11, 3, 57, 851645, tzinfo=utc)),
        ),
    ]
