# Generated by Django 3.2.8 on 2022-01-23 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0053_auto_20220123_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arming_log',
            name='signature',
        ),
        migrations.AddField(
            model_name='arming_log',
            name='signature_in',
            field=models.TextField(blank=True, null=True, verbose_name='חתימת כניסה'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='signature_out',
            field=models.TextField(blank=True, null=True, verbose_name='חתימת יציאה'),
        ),
        migrations.AlterField(
            model_name='arming_log',
            name='valid_in',
            field=models.TextField(blank=True, null=True, verbose_name='חתימת מנהל כניסה'),
        ),
        migrations.AlterField(
            model_name='arming_log',
            name='valid_out',
            field=models.TextField(blank=True, null=True, verbose_name='חתימת מנהל יציאה'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 23, 14, 19, 39, 638711, tzinfo=utc)),
        ),
    ]
