# Generated by Django 3.2.8 on 2022-01-23 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0054_auto_20220123_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 23, 14, 46, 57, 849821, tzinfo=utc)),
        ),
    ]
