# Generated by Django 3.2.8 on 2022-01-24 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0055_alter_week_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationlog',
            name='sig_a',
            field=models.TextField(blank=True, null=True, verbose_name='חתימה צהריים'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='sig_m',
            field=models.TextField(blank=True, null=True, verbose_name='חתימה בוקר'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='sig_n',
            field=models.TextField(blank=True, null=True, verbose_name='חתימה לילה'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 11, 43, 14, 71179, tzinfo=utc)),
        ),
    ]
