# Generated by Django 3.2.8 on 2022-02-03 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0059_auto_20220203_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 15, 43, 23, 750605, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ArmingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(default='', max_length=9, verbose_name='תעודת זהות')),
                ('shift_num', models.IntegerField(default=1, verbose_name='מספר משמרת')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('time_in', models.TimeField(default=django.utils.timezone.now, verbose_name='זמן כניסה')),
                ('num_mags', models.IntegerField(default=2, verbose_name='מספר מחסניות')),
                ('hand_cuffs', models.IntegerField(default=6, verbose_name='אזיקים')),
                ('gun_case', models.IntegerField(default=6, verbose_name='פונדה')),
                ('mag_case', models.IntegerField(default=6, verbose_name='נרתיק')),
                ('keys', models.BooleanField(default=False, verbose_name='מפתחות')),
                ('radio', models.BooleanField(default=False, verbose_name='קשר')),
                ('radio_kit', models.BooleanField(default=False, verbose_name='ערכת שמע')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='זמן יציאה')),
                ('valid_in', models.TextField(blank=True, null=True, verbose_name='חתימת מנהל כניסה')),
                ('valid_out', models.TextField(blank=True, null=True, verbose_name='חתימת מנהל יציאה')),
                ('signature_in', models.TextField(blank=True, null=True, verbose_name='חתימת כניסה')),
                ('signature_out', models.TextField(blank=True, null=True, verbose_name='חתימת יציאה')),
                ('read', models.BooleanField(default=False, verbose_name='טופל?')),
                ('reason', models.TextField(default='', verbose_name='סיבה')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.gun', verbose_name='מספר נשק')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.arming_log', verbose_name='הזנה ביומן חימוש')),
            ],
        ),
    ]
