# Generated by Django 3.2.8 on 2022-02-03 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0062_auto_20220203_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armingrequest',
            options={'verbose_name': 'בקשה לשינוי יומן חימוש', 'verbose_name_plural': 'בקשות לשינוי יומן חימוש'},
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 20, 17, 38, 868405, tzinfo=utc)),
        ),
    ]
