# Generated by Django 3.2.8 on 2022-02-07 09:17

import collections
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0063_auto_20220203_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 9, 17, 33, 143550, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ShiftOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.organization')),
            ],
        ),
    ]
