# Generated by Django 3.2.8 on 2022-02-07 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0065_auto_20220207_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 9, 57, 42, 285566, tzinfo=utc)),
        ),
    ]
