# Generated by Django 3.2.8 on 2022-02-07 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0066_alter_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 11, 11, 23, 822325, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ShiftOrganizer',
        ),
    ]
